# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#package-ecosystem-

version: 2
updates:
  - package-ecosystem: "github-actions" # .github/workflows/*.yml
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo" # Cargo.lock
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo" # Cargo.lock
    target-branch: "main"
    directory: "/crates/code2prompt-core"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip" # pyproject.toml
    target-branch: "main"
    directory: "/crates/code2prompt-python"
    schedule:
      interval: "weekly"
  - package-ecosystem: "uv" # requirements.lock
    target-branch: "main"
    directory: "/crates/code2prompt-python"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" # package.json and yarn.lock
    target-branch: "main"
    directory: "/website"
    schedule:
      interval: "weekly"
