[package]
name = "code2prompt"
version = "3.0.0"
authors = ["Mufeed VH <mufeed@lyminal.space>", "Olivier D'Ancona <olivier.dancona@master.hes-so.ch>"]
description = "A command-line (CLI) tool to generate an LLM prompt from codebases of any size, fast."
keywords = ["code", "prompt", "llm", "gpt", "ai", "agent", "glob"]
categories = ["command-line-utilities", "development-tools"]
homepage = "https://github.com/mufeedvh/code2prompt"
documentation = "https://github.com/mufeedvh/code2prompt"
repository = "https://github.com/mufeedvh/code2prompt"
license = "MIT"
readme = "README.md"
exclude = [".github/*", ".assets/*"]
edition = "2021"
build = "build.rs"

[features]
default = ["cli"]
cli = ["dep:clap", "dep:env_logger", "dep:arboard"]
bindings = ["dep:pyo3"]

[dependencies]
log = "0.4"
handlebars = "4.3"
jwalk = "0.8"
termtree = "0.4"
serde_json = "1.0.114"
indicatif = "0.17.8"
colored = "2.1.0"
tiktoken-rs = "0.6.0"
ignore = "0.4.22"
anyhow = "1.0.80"
inquire = "0.7.1"
regex = "1.10.3"
git2 = { version = "0.18.2", default-features = false, features = ["https", "vendored-libgit2", "vendored-openssl"] }
glob = "0.3.1"
once_cell = "1.19.0"
globset = "0.4.15"
num-format = { version = "0.4.4", features = ["with-system-locale"] }

# cli dependencies
clap = { version = "4.0", features = ["derive"], optional = true }
env_logger = { version = "0.11.3", optional = true }
arboard = { version = "3.4.0", optional = true }

# bindings dependencies
pyo3 = { version = "0.23", features = ["extension-module", "abi3-py312", "generate-import-lib"], optional = true }

[lib]
name = "code2prompt"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = "thin"
panic = 'abort'
codegen-units = 1

[package.metadata.deb]
section = "utility"
assets = [
    ["target/release/code2prompt", "/usr/bin/", "755"],
]

[dev-dependencies]
tempfile = "3.3"
assert_cmd = "2.0"
predicates = "2.0"
env_logger = "0.11.3"
