[package]
name = "code2prompt"
version = "3.0.0"
edition = "2021"
description = "Command-line interface for code2prompt"
license = "MIT"
repository = "https://github.com/mufeedvh/code2prompt"

[dependencies]
code2prompt_core = { path = "../code2prompt-core" }
clap = { version = "4.0", features = ["derive"] }
env_logger = { version = "0.11.3" }
arboard = { version = "3.4.0" }
anyhow = { workspace = true }
colored = { workspace = true }
indicatif = { workspace = true }
log = { workspace = true }
num-format = { workspace = true }
serde_json = { workspace = true }

[[bin]]
name = "code2prompt_core"
path = "src/main.rs"
